services:
  grok2api_python:
    image: yxmiler/grok2api_python:latest
    container_name: grok2api_python
    ports:
      - "3000:3000"
    environment:
      - API_KEY=your_api_key
      - TUMY_KEY=你的图床key,和PICGO_KEY 二选一
      - PICGO_KEY=你的图床key,和TUMY_KEY二选一
      - IS_TEMP_CONVERSATION=true
      - IS_CUSTOM_SSO=true
      - ISSHOW_SEARCH_RESULTS=false
      - PORT=3000
      - SHOW_THINKING=true
      - SSO=your_sso
      - PROXY_URL_POOL=socks5://warp:1080 
    restart: unless-stopped

  warp:
    image: caomingjun/warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600 --label-enable 